### PR TITLE
Creates a Profile Page

### LINKED ISSUE #9: Create a "view profile" screen
See the design proposed by our designer Nidhi for the profile page [here](https://www.figma.com/proto/USIHfS9Ut2gFMNqUZprrnEzT/UCLA-Eats?scaling=contain&node-id=1%3A177) and design a screen according to that specification.

Note: Depending on further discussions, we might add an option to view the user's bio on this screen too, so maybe design with that in mind.  

Attached image below for easier reference.

screen shot 2018-04-21 at 2 35 20 am

### PR DESCRIPTION
**Pull request by sjl1826**
fixes #9

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@sjl1826, can you post screenshots of the new screen that you added in this PR?

**Comment by sjl1826** [comment]
screen shot 2018-04-30 at 1 11 53 pm

**Comment by sjl1826** [comment]
screen shot 2018-04-30 at 1 13 01 pm

**Comment by HirdayGupta** [comment]
Closed by #24

**Pull request closed without merging**
